"""Label manager: load, validate, merge, and deduplicate ground truth labels.

Labels live in ``data/labels/`` as JSONL files. Anyone can drop labeled data
into that directory and the system immediately uses it.

Trust tiers (used for deduplication when the same raw_line appears in
multiple label files):
    human      -- Gold. Human-verified. Highest trust.
    llm_judge  -- Silver. Generated by a strong model.
    synthetic  -- Bronze. Generated by a synthetic data generator.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from chat_to_cop.models.cop_update import UpdateType

# Canonical trust ordering: lower index = higher trust
TRUST_ORDER: list[str] = ["human", "llm_judge", "synthetic"]

# Required fields every label must have
REQUIRED_FIELDS: list[str] = ["raw_line", "channel", "source"]

# Valid values for the 'source' field
VALID_SOURCES: set[str] = set(TRUST_ORDER)

# Valid update types (derived from the UpdateType enum + the silver-label
# field names used by the existing generate_silver_labels.py script)
VALID_TYPES: set[str] = {t.value for t in UpdateType}


def _trust_rank(source: str) -> int:
    """Return an integer rank for a source tier (lower = more trusted)."""
    try:
        return TRUST_ORDER.index(source)
    except ValueError:
        return len(TRUST_ORDER)  # unknown sources rank below bronze


def load_labels(labels_dir: str = "data/labels/") -> list[dict]:
    """Discover all ``.jsonl`` files in *labels_dir*, load them, and deduplicate.

    When the same ``raw_line`` appears in multiple files with different
    ``source`` values, the highest-trust version wins (human > llm_judge >
    synthetic).

    Returns:
        A list of label dicts, one per unique ``raw_line``.
    """
    labels_path = Path(labels_dir)
    if not labels_path.is_dir():
        return []

    # Collect all labels across every JSONL file
    all_labels: list[dict] = []
    for jsonl_file in sorted(labels_path.glob("*.jsonl")):
        with open(jsonl_file, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    all_labels.append(json.loads(line))
                except json.JSONDecodeError:
                    continue

    # Deduplicate by raw_line, keeping the highest-trust version
    best: dict[str, dict] = {}
    for label in all_labels:
        raw = label.get("raw_line", "")
        source = label.get("source", "")
        existing = best.get(raw)
        if existing is None or _trust_rank(source) < _trust_rank(existing.get("source", "")):
            best[raw] = label

    return list(best.values())


def validate_label(label: dict) -> list[str]:
    """Return a list of validation errors for a single label dict.

    An empty list means the label is valid.
    """
    errors: list[str] = []

    for field in REQUIRED_FIELDS:
        if field not in label or not label[field]:
            errors.append(f"missing '{field}'")

    source = label.get("source", "")
    if source and source not in VALID_SOURCES:
        errors.append(f"invalid source '{source}' (expected one of {sorted(VALID_SOURCES)})")

    # Validate expected_type if present (the canonical label field)
    expected_type = label.get("expected_type")
    if expected_type is not None and expected_type not in VALID_TYPES:
        errors.append(f"invalid type '{expected_type}' (expected one of {sorted(VALID_TYPES)})")

    # Also validate extracted_type for backward compat with silver labels
    extracted_type = label.get("extracted_type")
    if extracted_type is not None and extracted_type not in VALID_TYPES:
        errors.append(f"invalid type '{extracted_type}' (expected one of {sorted(VALID_TYPES)})")

    return errors


def label_stats(labels: list[dict]) -> dict:
    """Return aggregate counts from a list of labels.

    Returns a dict with keys:
        total    -- total label count
        by_source -- Counter of source values
        by_type  -- Counter of expected_type (falls back to extracted_type)
        by_channel -- Counter of channel values
    """
    by_source: Counter[str] = Counter()
    by_type: Counter[str] = Counter()
    by_channel: Counter[str] = Counter()

    for label in labels:
        by_source[label.get("source", "unknown")] += 1
        # Prefer expected_type (gold/silver label field), fall back to extracted_type (silver-gen output)
        utype = label.get("expected_type") or label.get("extracted_type") or "unknown"
        by_type[utype] += 1
        by_channel[label.get("channel", "unknown")] += 1

    return {
        "total": len(labels),
        "by_source": dict(by_source),
        "by_type": dict(by_type),
        "by_channel": dict(by_channel),
    }


def merge_labels(existing_path: str | Path, new_labels: list[dict]) -> int:
    """Append *new_labels* to a JSONL file, skipping duplicates.

    Duplicates are detected by ``raw_line``. Existing lines in the file
    are loaded first to build the dedup set.

    Returns:
        The number of labels actually written (i.e., non-duplicates).
    """
    existing_path = Path(existing_path)
    existing_path.parent.mkdir(parents=True, exist_ok=True)

    # Load existing raw_lines for dedup
    seen: set[str] = set()
    if existing_path.exists():
        with open(existing_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                    seen.add(obj.get("raw_line", ""))
                except json.JSONDecodeError:
                    continue

    added = 0
    with open(existing_path, "a", encoding="utf-8") as f:
        for label in new_labels:
            raw = label.get("raw_line", "")
            if raw in seen:
                continue
            f.write(json.dumps(label, ensure_ascii=False) + "\n")
            seen.add(raw)
            added += 1

    return added
